spring:
  datasource:
    url: jdbc:mysql://localhost:3306/usertable
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

gowtham:
  app:
    jwtSecret: BB87E98B15ECC65385296DF62D167
    jwtExpirationMs: 86400000
